### PR TITLE
fix for Router.ready()

### PR DESCRIPTION
**Pull request by comerc**

### CODE REVIEW

**Comment by comerc** [comment]
Why unmerged? 😆

**Comment by nate-strauser** [comment]
i'm refactoring the app currently...

also i'm not sure a `this.ready()` check is really needed - the guide
doesn't show anything like that
https://github.com/EventedMind/iron-router/blob/devel/Guide.md#rendering-templates-with-data
- i'm ok with partial rendering and then rerendering, if that's what the
ready call is supposed to fix

**Comment by comerc** [comment]
https://github.com/EventedMind/iron-router/blob/e1666f5cdd2139b63dbc23b28d21d029387832a5/Guide.md#the-waiton-option

When router renders a loadingTemplate, this.ready() is false.

**Comment by nate-strauser** [comment]
correct - so this.ready() would be needed if we used `subscribe`, but since we use `waitOn` we don't need to do that

from the guide 
```
Another alternative is to use waitOn instead of subscribe. This has the same effect but automatically short-circuits your route action and any before hooks (see below), and renders a loadingTemplate instead.
```

**Comment by comerc** [comment]
You may try use console.log for this.ready()

**Comment by comerc** [comment]
You are right. Sorry. 😇

**Pull request closed without merging**
