### PR TITLE
Vanity urls for Jobs and Profiles. Closes #43

### LINKED ISSUE #43: Profile and Jobs should have vanity urls
/jobs/<id>/<title>  title is optional
/profiles/<id>/<displayName>  title is optional

### PR DESCRIPTION
**Pull request by jorisbontje**
@nate-strauser please review before merging!

I am not 100% happy with the duplication in `server/api.js`. Do you know how I can use Collection Helpers there?

### CODE REVIEW

**Comment by jorisbontje** [comment]
rebased...

**Comment by jorisbontje** [comment]
@nate-strauser would you be okay with merging this as-is?

**Comment by nate-strauser** [comment]
i think this looks fine, i just haven't gotten around to testing it out -- i'll get it done this week

**Comment by nate-strauser** [comment]
thanks for this - made a couple minor tweaks, but overall worked quite well

**Comment by jorisbontje** [comment]
Thanks :D Looking sharp!

**Pull request merged**
