### PR TITLE
update Meteor release 1.3.4.1

### PR DESCRIPTION
**Pull request by alextaaa**

### CODE REVIEW

**Comment by nate-strauser** [comment]
overall this looks good to me, but what's with the changes to the .less files?  it's odd to change the import path in comments like that.  is that something your editor did automatically?

if you can remove the .less changes and reinstate my sublime project file, i'll merge this in

thanks!

**Comment by alextaaa** [comment]
Hello. 
Thank you for feedback ) 
Maybe it is bug or not ))
If I started Meteor and > git status, I see 
 > modified:   client/lib/custom.bootstrap.less
 > modified:   client/lib/custom.bootstrap.mixins.import.less

Maybe add files into gitignore ?

**Comment by alextaaa** [comment]
New pull req https://github.com/nate-strauser/wework/pull/104

**Comment by nate-strauser** [comment]
what OS and editor are you using?  i'm thinking that the file paths are
getting automatically rewritten when you open the project/directory.

i can't add those to .gitignore as they are needed for styling the app, so
I do want them in the build

**Comment by alextaaa** [comment]
I use Windows 10 and Sublime Text 3

**Comment by alextaaa** [comment]
But I have all OS and can start project on Linux or on MacOs

But problem persist

**Comment by nate-strauser** [comment]
dupe

**Pull request closed without merging**
